### ISSUE TITLE
Incorrect padding removal

### ISSUE THREAD

**Issue by jsharkey13** [avibrazil/iOSbackup#1]
Hi, I notice your code is based on the Google [iphone-dataprotection](https://code.google.com/p/iphone-dataprotection/) code, which I am using in a similar project. Someone [reported a bug in my code](https://github.com/jsharkey13/iphone_backup_decrypt/issues/1), and it looks like yours has the same problem - so I thought I'd let you know too.

Like me, you're using the `Size` property from the Manifest file to truncate the decrypted data; it turns out that sometimes this value is shorter than the true byte length of the file, and you inadvertantly remove real file data leading to corruption. You do this [here](https://github.com/avibrazil/iOSbackup/blob/b7ac700569ae005b341ae7098436d1652684ffcd/iOSbackup/__init__.py#L558). The original Google code moved away from this, and used a `padding=True` argument to `AESdecryptCBC` which you seem to have, but without the referenced [`removePadding` function](https://github.com/avibrazil/iOSbackup/blob/b7ac700569ae005b341ae7098436d1652684ffcd/iOSbackup/__init__.py#L810).

The missing function was:
```python
def removePadding(blocksize, s):
    'Remove rfc 1423 padding from string.'
    n = ord(s[-1]) # last byte contains number of padding bytes
    if n > blocksize or n > len(s):
        raise Exception('invalid padding')
    return s[:-n]
```

then you can just [modify your code from](https://github.com/avibrazil/iOSbackup/blob/b7ac700569ae005b341ae7098436d1652684ffcd/iOSbackup/__init__.py#L558)
```python
dataDecrypted = iOSbackup.AESdecryptCBC(dataEncrypted, key)[:fileData['Size']]
```
to
```python
dataDecrypted = iOSbackup.AESdecryptCBC(dataEncrypted, key, padding=True)
```
to fix this bug. I couldn't get your code to run on Windows, so I couldn't easily test this to make a pull request.

**Comment by avibrazil** [comment]
I'm changing the code to incorporate your suggestion and a new release will come soon.

**Comment by avibrazil** [comment]
This suggestion was incorporated in the new release. Please `pip3 install -U iOSbackup —user` to use it.
