### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by botherder** [avibrazil/iOSbackup#11]
Firstly, thank you very much for writing this code and making it publicly available. It would be important however that you pick and provide a license for use of your code. The general assumption for code published without a license is that all rights are reserved, and as such that means people can not make any use of the code you release, other than looking at it. If your intention is instead for others to make use of your tool, a LICENSE file would help :).

**Comment by rinsuki** [comment]
It looks LGPL? https://github.com/avibrazil/iOSbackup/blob/64be52bf554523db11888c7a02ea5675527cb0d5/setup.py#L29

**Comment by botherder** [comment]
Oh ok, I did notice this. Thanks.
