### ISSUE TITLE
Python 3.8

### ISSUE THREAD

**Issue by botherder** [avibrazil/iOSbackup#19]
I noticed that your setup.py indicates that Python >= 3.8 is required. Because Python 3.7 is still the default on many installations and OSes, this is causing some installation issues. Is there a particular reason to require 3.8?
Thank you.

**Comment by avibrazil** [comment]
I don't remember anymore.
I only use 3.9 and up in all my systems.
Please let me know if it was usable in 3.7

**Comment by avibrazil** [comment]
I can't remember anymore why I put Python 3.8 as a restriction.
Please someone force an installation on older Python and let me know if it works, then I'll reduce the version requirement.

**Comment by Te-k** [comment]
Hi,
I just tested iOSbackup with python 3.8 and decrypted a backup and didn't have any problem. Is there anything specific or test script I should use to confirm that there is no compatibility issue?

**Comment by avibrazil** [comment]
What about 3.7?

**Comment by Te-k** [comment]
It also seems to work with iOS 3.7.0 so it should be good for all 3.7 versions

**Comment by botherder** [comment]
Just checking in if there are any developments on this?

**Comment by avibrazil** [comment]
New version 0.9.924 now requires Python 3.7

**Comment by Te-k** [comment]
Actually, iOSbackup relies on [avibrazil/NSKeyedUnArchiver](https://github.com/avibrazil/NSKeyedUnArchiver) which also requires python 3.8. If I am right, this is based on the need for UID support in plistlib which was added in python 3.8, so not sure if there is anything to do there.

**Comment by avibrazil** [comment]
That’s correct.

iOSbackup requires [avibrazil/NSKeyedUnArchiver](https://github.com/avibrazil/NSKeyedUnArchiver) (which I wrote it myself) which in turns requires plistlib with features that appeared on Python 3.8 only.

So Python 3.8 is indeed the minimum.

Currently Python is 3.11. Why are there people still relying on old 3.7?

**Comment by Te-k** [comment]
I am not sure, but we aren't going to try to push for 3.7 support in MVT in any case. Thanks anyway for being open to do that
